name: inspired-dev
channels:
  - conda-forge
  - pytorch
dependencies:
  - anaconda-client
  - boa
  - check-wheel-contents
  - conda-build
  - conda-verify
  - pre-commit
  - python == 3.9
  - python-build
  - pymatgen==2024.5.1
  - spglib==2.4.0
  - versioningit
  - pandas
  - pyqt >= 5, <6
  - qtpy
  - phonopy
  - seekpath
  - matgl
  - chgnet
  - mkl==2024.0 # resolve the pytorch error
  - pytorch
  - pip
  - pip:
    - mace-torch
    - torch-geometric
    - torch-sparse 
    - torch-cluster
    - torch-scatter 